### ISSUE TITLE
Exception thrown: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V: co

### ISSUE THREAD

**Issue by MaximeBernard** [johnlindquist/angularjs-plugin#34]
I just opened my project and PHPStorm told me this exception has been thrown. 

It might be related to the fact I lost connection to my mounted drive I was working on earlier ?

**Comment by dryaf** [comment]
+1

i did cmd+L on a mac

**Comment by johnlindquist** [comment]
Which version of PhpStorm/WebStorm/whatever are you guys using?

**Comment by dryaf** [comment]
rubymine 5.4.3.2.1  ;-) no joke

angular plugin 0.1.9

com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
java.lang.NoSuchMethodError: com.intellij.find.impl.FindInProjectUtil.findUsages(Lcom/intellij/find/FindModel;Lcom/intellij/psi/PsiDirectory;Lcom/intellij/openapi/project/Project;ZLcom/intellij/util/Processor;Lcom/intellij/usages/FindUsagesProcessPresentation;)V
    at org.angularjs.GotoAngularAction.getAngularUsages(GotoAngularAction.java:190)
    at org.angularjs.GotoAngularAction.gotoActionPerformed(GotoAngularAction.java:80)
    at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:60)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:494)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by hho** [comment]
Happens on IntelliJ IDEA 12.1.6 (129.1359) as well (press Ctrl-L on Windows).
Stacktrace is basically the same as above (only AWT has different line numbers here).

**Comment by technixp** [comment]
+1 
Same on phpStorm 7.1 build version 133.326
adding this plugin makes phpStorm unusable

**Comment by denofevil** [comment]
This issue should be fixed with JetBrains/intellij-plugins@1ddd37c13c64ad31d7397d8472b950cb65c8fbc2

**Comment by lukaszkusy** [comment]
+1
Still occurs
Plugin 0.1.9
Intellij IDEA 12.1.7 Build IU-129.1521
